#maximum money for the server
global_max_money: 10000
#amount of precent to deduct from someone who has died to another player
deduct_amount_precent: 70
#default save path
#I recommend not touching this in fear of breaking stuff
currency_save_path: "./plugins/btelnyy-social-currency-expierement/CurrencyData/"
#how much money should every player receive after joining for the first time?
player_starting_money: 0
#what is the currency symbol?
currency_symbol: "$"