name: btelnyy-social-currency-expierement
main: btelnyy.plugin.Main
version: 1.0.0
api-version: 1.18
commands:
   pay:
      description: Pay another player
      usage: /pay <target> <amount>
      permission: btelnyy.command.pay