#maximum money for the server
#this is not used
global_max_money: 10000
#amount of percent to deduct from someone who has died to another player
deduct_amount_precent: 70
#what percent of money to deduct on a players natural (non-pvp) death?
currency_deduct_amount_natural: 20
#default save path
#what is the data folders name?
currency_save_path: "CurrencyData"
#how much money should every player receive after joining for the first time?
player_starting_money: 0
#what is the currency symbol?
currency_symbol: "$"
#what is the maximum amount of money that a player can withdraw per /withdraw ?
#set to 0 if you want to disable
max_withdraw_amount: 0
#disable global transactions between players, does not affect admin commands
no_player_transactions: false
#a setting for dev only things, do not enable unless you like half broken commands
debug: false