name: btelnyy-currency
main: me.btelnyy.currency.CurrencyPlugin
version: ${project.version}
api-version: 1.18
commands:
   pay:
      description: Pay another player
      usage: /pay <target> <amount>
      permission: btelnyy.command.pay
   bal:
      description: View your balance
      usage: /bal
      permission: btelnyy.command.balance
   balance:
      description: View your balance
      usage: /balance
      permission: btelnyy.command.balance
   currencyreset:
      description: Reset a player
      usage: /currencyreset <target>
      permission: btelnyy.command.currencyreset
   setmoney:
      description: Set an amount of money to a player
      usage: /setmoney <target> <amount>
      permission: btelnyy.command.setmoney
   togglepay:
      description: Toggle if a player can pay others
      usage: /togglepay <player>
      permission: btelnyy.command.togglepay
   togglepaid:
      description: Toggle if a player can get money from others
      usage: /togglepaid <player>
      permission: btelnyy.command.togglepaid
